"""empty message

Revision ID: 07232a61984b
Revises: fe9cd5c0e915
Create Date: 2024-09-23 23:02:46.798704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07232a61984b'
down_revision = 'fe9cd5c0e915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('plantsitter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_post.id'], ),
    sa.ForeignKeyConstraint(['plantsitter_id'], ['plant_sitters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_assignments')
    # ### end Alembic commands ###
