"""empty message

Revision ID: 1835bb256b3f
Revises: 4ec456287d45
Create Date: 2024-09-13 23:50:32.617857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1835bb256b3f'
down_revision = '4ec456287d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.drop_column('extra_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_info', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
