"""empty message

Revision ID: 242c4e90bd7d
Revises: 95e256e7d412
Create Date: 2024-08-31 01:28:00.864025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242c4e90bd7d'
down_revision = '95e256e7d412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_sitters', schema=None) as batch_op:
        batch_op.drop_column('additional_info')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_sitters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('additional_info', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
