"""empty message

Revision ID: 31b79fa431fb
Revises: bc9b132c6fa7
Create Date: 2024-09-05 23:48:06.493853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b79fa431fb'
down_revision = 'bc9b132c6fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.drop_column('job_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
