"""empty message

Revision ID: 3c8c53e76bfe
Revises: a11d099c4bc3
Create Date: 2024-09-26 20:58:19.364188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c8c53e76bfe'
down_revision = 'a11d099c4bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gif_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('message_content',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('message_content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('gif_url')

    # ### end Alembic commands ###
