"""empty message

Revision ID: 5d2009a0e384
Revises: cf21812b3a90
Create Date: 2024-08-30 23:53:15.942576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2009a0e384'
down_revision = 'cf21812b3a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_sitters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_sitters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###
