"""empty message

Revision ID: 68693213745f
Revises: 3932221cb789
Create Date: 2024-08-27 23:22:55.222890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68693213745f'
down_revision = '3932221cb789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
