"""empty message

Revision ID: 6e533c712c51
Revises: 3827c15ccb3c
Create Date: 2024-09-25 02:18:14.065153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e533c712c51'
down_revision = '3827c15ccb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_marked_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('plantsitter_marked_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_assignments', schema=None) as batch_op:
        batch_op.drop_column('plantsitter_marked_completed')
        batch_op.drop_column('client_marked_completed')

    # ### end Alembic commands ###
