"""empty message

Revision ID: 760c23eed1e4
Revises: 40d3ccd22856
Create Date: 2024-08-24 22:21:26.478180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760c23eed1e4'
down_revision = '40d3ccd22856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))

    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_profiles_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('job_post_plant_sitter_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'client_profiles', ['client_profiles_id'], ['id'])
        batch_op.drop_column('plant_sitter_id')

    with op.batch_alter_table('plant_sitters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_line_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('professional_experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone')

    with op.batch_alter_table('plant_sitters', schema=None) as batch_op:
        batch_op.drop_column('additional_info')
        batch_op.drop_column('professional_experience')
        batch_op.drop_column('bio')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('address_line_1')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_sitter_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_post_plant_sitter_id_fkey', 'plant_sitters', ['plant_sitter_id'], ['id'])
        batch_op.drop_column('client_profiles_id')

    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('address_line_1')

    # ### end Alembic commands ###
