"""empty message

Revision ID: 862f694900c3
Revises: 64e429dbd6cf
Create Date: 2024-09-23 14:40:36.878843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862f694900c3'
down_revision = '64e429dbd6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.alter_column('intro',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('more_about_your_plants',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('more_about_services',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('job_duration',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.alter_column('job_duration',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('more_about_services',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('more_about_your_plants',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('intro',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
