"""empty message

Revision ID: 8964d4085662
Revises: 242c4e90bd7d
Create Date: 2024-09-05 00:55:46.570719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8964d4085662'
down_revision = '242c4e90bd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key from job_post to client_profiles
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.drop_constraint('job_post_client_profiles_id_fkey', type_='foreignkey')
        batch_op.drop_column('client_profiles_id')

    # Drop the client_profiles table
    op.drop_table('client_profiles')

    # Add new columns to job_post table
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('my_plants', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore columns and constraints in the job_post table
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.drop_column('my_plants')
        batch_op.drop_column('service_preferences')
        batch_op.add_column(sa.Column('client_profiles_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('job_post_client_profiles_id_fkey', 'client_profiles', ['client_profiles_id'], ['id'])

    # Restore the client_profiles table
    op.create_table('client_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('my_plants', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='client_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='client_profiles_pkey')
    )
    # ### end Alembic commands ###