"""empty message

Revision ID: 95e256e7d412
Revises: 5d2009a0e384
Create Date: 2024-08-31 00:20:38.796657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e256e7d412'
down_revision = '5d2009a0e384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_sitters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_plants', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extra_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_sitters', schema=None) as batch_op:
        batch_op.drop_column('extra_info')
        batch_op.drop_column('client_info')
        batch_op.drop_column('current_plants')
        batch_op.drop_column('intro')

    # ### end Alembic commands ###
