"""empty message

Revision ID: a442d6823c45
Revises: ce58679ab7ef
Create Date: 2024-09-13 21:29:12.000372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a442d6823c45'
down_revision = 'ce58679ab7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.drop_column('extra_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_info', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
