"""empty message

Revision ID: b296f2d0e348
Revises: 760c23eed1e4
Create Date: 2024-08-25 19:28:31.810305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b296f2d0e348'
down_revision = '760c23eed1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sitter_id', sa.Integer(), nullable=False),
    sa.Column('rating_value', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sitter_id'], ['plant_sitters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('address_line_1')
        batch_op.drop_column('location')
        batch_op.drop_column('country')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('address_line_2')

    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.drop_column('rate')

    with op.batch_alter_table('plant_sitters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_plants', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('city')
        batch_op.drop_column('address_line_1')
        batch_op.drop_column('location')
        batch_op.drop_column('country')
        batch_op.drop_column('longitude')
        batch_op.drop_column('prefered_plants')
        batch_op.drop_column('latitude')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('address_line_2')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('location')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('address_line_1')

    with op.batch_alter_table('plant_sitters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line_2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('prefered_plants', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address_line_1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('preferred_plants')

    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line_2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address_line_1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    op.drop_table('rating')
    # ### end Alembic commands ###
