"""empty message

Revision ID: bc9b132c6fa7
Revises: 8964d4085662
Create Date: 2024-09-05 01:31:06.710542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9b132c6fa7'
down_revision = '8964d4085662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('intro', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('more_about_your_plants', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('more_about_services', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extra_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('job_duration', sa.String(length=100), nullable=True))
        batch_op.drop_column('details')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('details', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('job_duration')
        batch_op.drop_column('job_description')
        batch_op.drop_column('extra_info')
        batch_op.drop_column('more_about_services')
        batch_op.drop_column('more_about_your_plants')
        batch_op.drop_column('intro')
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###
